# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_BUILD_SOURCE_DIRS "/Users/maestrotrastanechora/Downloads/New OTTD/openttd-1.11.2;/Users/maestrotrastanechora/Downloads/New OTTD/openttd-1.11.2/build")
set(CPACK_BUNDLE_ICON "/Users/maestrotrastanechora/Downloads/New OTTD/openttd-1.11.2/os/macosx/openttd.icns")
set(CPACK_BUNDLE_NAME "OpenTTD")
set(CPACK_BUNDLE_PLIST "/Users/maestrotrastanechora/Downloads/New OTTD/openttd-1.11.2/build/Info.plist")
set(CPACK_BUNDLE_PLIST_SOURCE "/Users/maestrotrastanechora/Downloads/New OTTD/openttd-1.11.2/build/Info.plist.in")
set(CPACK_CMAKE_GENERATOR "Unix Makefiles")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "/usr/local/Cellar/cmake/3.20.3/share/cmake/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "openttd built using CMake")
set(CPACK_DMG_BACKGROUND_IMAGE "/Users/maestrotrastanechora/Downloads/New OTTD/openttd-1.11.2/os/macosx/splash.png")
set(CPACK_DMG_FORMAT "UDBZ")
set(CPACK_GENERATOR "Bundle")
set(CPACK_INSTALL_CMAKE_PROJECTS "/Users/maestrotrastanechora/Downloads/New OTTD/openttd-1.11.2/build;openttd;ALL;/")
set(CPACK_INSTALL_PREFIX "/usr/local")
set(CPACK_MODULE_PATH "/Users/maestrotrastanechora/Downloads/New OTTD/openttd-1.11.2/cmake")
set(CPACK_MONOLITHIC_INSTALL "YES")
set(CPACK_NSIS_DISPLAY_NAME "OpenTTD")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
set(CPACK_NSIS_PACKAGE_NAME "OpenTTD")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_OSX_SYSROOT "/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk")
set(CPACK_OUTPUT_CONFIG_FILE "/Users/maestrotrastanechora/Downloads/New OTTD/openttd-1.11.2/build/CPackConfig.cmake")
set(CPACK_OUTPUT_FILE_PREFIX "bundles")
set(CPACK_PACKAGE_CHECKSUM "SHA256")
set(CPACK_PACKAGE_CONTACT "OpenTTD <info@openttd.org>")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION "OpenTTD")
set(CPACK_PACKAGE_DESCRIPTION_FILE "/usr/local/Cellar/cmake/3.20.3/share/cmake/Templates/CPack.GenericDescription.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "OpenTTD")
set(CPACK_PACKAGE_EXECUTABLES "openttd;OpenTTD")
set(CPACK_PACKAGE_FILE_NAME "openttd-#CPACK_PACKAGE_VERSION#-macos-amd64")
set(CPACK_PACKAGE_HOMEPAGE_URL "https://www.openttd.org/")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "OpenTTD")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "OpenTTD")
set(CPACK_PACKAGE_NAME "openttd")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "OpenTTD")
set(CPACK_PACKAGE_VERSION "1.11.2")
set(CPACK_PACKAGE_VERSION_MAJOR "1")
set(CPACK_PACKAGE_VERSION_MINOR "11")
set(CPACK_PACKAGE_VERSION_PATCH "2")
set(CPACK_RESOURCE_FILE_LICENSE "/Users/maestrotrastanechora/Downloads/New OTTD/openttd-1.11.2/build/COPYING.rtf")
set(CPACK_RESOURCE_FILE_README "/Users/maestrotrastanechora/Downloads/New OTTD/openttd-1.11.2/README.md")
set(CPACK_RESOURCE_FILE_WELCOME "/usr/local/Cellar/cmake/3.20.3/share/cmake/Templates/CPack.GenericWelcome.txt")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_GENERATOR "TBZ2;TGZ;TXZ;TZ")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/Users/maestrotrastanechora/Downloads/New OTTD/openttd-1.11.2/build/CPackSourceConfig.cmake")
set(CPACK_SOURCE_RPM "OFF")
set(CPACK_SOURCE_TBZ2 "ON")
set(CPACK_SOURCE_TGZ "ON")
set(CPACK_SOURCE_TXZ "ON")
set(CPACK_SOURCE_TZ "ON")
set(CPACK_SOURCE_ZIP "OFF")
set(CPACK_STRIP_FILES "YES")
set(CPACK_SYSTEM_NAME "amd64")
set(CPACK_THREADS "1")
set(CPACK_TOPLEVEL_TAG "amd64")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/Users/maestrotrastanechora/Downloads/New OTTD/openttd-1.11.2/build/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
